version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    volumes:
      - .:/app
      - sqlite_data:/home/igor/Documentos/Estudos/Express/MyWay/models/shopper.db
    command: npm start

volumes:
  sqlite_data: